_G.Core = {
    disabled_builtins = {
        "netrw",
        "netrwPlugin",
        "netrwSettings",
        "netrwFileHandlers",
        "gzip",
        "zip",
        "zipPlugin",
        "tar",
        "tarPlugin",
        "getscript",
        "getscriptPlugin",
        "vimball",
        "vimballPlugin",
        "2html_plugin",
        "logipat",
        "matchit",
        "rrhelper",
        "spellfile_plugin",
    },
    global_options = {
        conceallevel = 1,
        fileencoding = "utf-8",
        pumheight = 10,
    },
    options = {
        autoread = true,
        backspace = { "indent", "eol", "start" },
        backup = false,
        clipboard = "unnamedplus",
        cmdheight = 1,
        cursorline = true,
        diffopt = { "internal", "algorithm:patience" },
        encoding = "UTF-8",
        expandtab = true,
        gdefault = true,
        hlsearch = true,
        ignorecase = true,
        iskeyword = { "-" },
        lazyredraw = true,
        magic = true,
        mouse = "a",
        number = true,
        numberwidth = 4,
        relativenumber = true,
        scrolloff = 8,
        shiftwidth = 4,
        shortmess = { c = true, I = true, s = true },
        showmode = false,
        showtabline = 2,
        sidescrolloff = 8,
        signcolumn = "yes",
        smartcase = true,
        smartindent = true,
        softtabstop = 4,
        spell = false,
        splitbelow = true,
        splitright = true,
        swapfile = false,
        termguicolors = true,
        timeoutlen = 100,
        undofile = true,
        updatetime = 300,
        whichwrap = "<>[]hl",
        wrap = false,
        writebackup = false,
    },
}
