-- THIS (`init.lua`) FILE WAS GENERATED BY HOME-MANAGER.
-- REFRAIN FROM MODIFYING IT DIRECTLY!

local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    _G.packer_bootstrap = fn.system({
        "git",
        "clone",
        "--depth",
        "1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    })
    print("Installing packer.nvim")
    vim.cmd([[packadd packer.nvim]])
end

-- Point Nvim to correct sqlite path
-- vim.g.sqlite_clib_path = "${pkgs.sqlite.out}/lib/libsqlite3.so"

-- Call-forward Agasaya:
require("core").init()
